### PR TITLE
Make option text fade if it overflows select element

### PR DESCRIPTION
**Pull request by skitson**
Where the text for a select option is lengthy, it can sometimes overflow the select element. This was happening a lot on Sky Mobile Services where the options are very long (especially on smaller screens). The result was that the text went underneath the select arrow (see second select example in image below).

A solution is to make the text appear to fade underneath the select arrow. I've done this by adding a `::before` pseudo element to the `.c-form-select` class with a linear gradient background (see first select example in image below).

screen shot 2016-08-12 at 13 45 53

### CODE REVIEW

**Comment by joebell93** [comment]
All good on IE9+ ?

**Comment by MrDinsdale** [comment]
Assuming the browsers all render fine I think its a much more graceful way of handling long option copy. :shipit:

**Comment by skitson** [comment]
I previewed this in a Windows 7 VM using IE9 and the gradient wasn't there - it was just a solid white background (in the before pseudo element). @MrDinsdale has suggested using a png or svg for the gradient as a base64 background image. Anyone have any thoughts on this?

I think it might be the best solution. If we use that, do we put the linear gradient css in for other browsers with a base64 fallback for IE9 or use the base64 image right across the board?

**Comment by joebell93** [comment]
I don't think there's any problem with that @skitson!

You can utilise the `ie9` conditional class set in [toolkit-core/utilities/ie9](https://github.com/sky-uk/toolkit-core/blob/master/utilities/_ie9.scss)

**Comment by skitson** [comment]
I've tried a few things in IE9 but can't come to a good solution. If I hook into the `.ie9` class and  add in the pseudo element with a png background, it covers the dropdown arrow. This is because it's the native arrow being generated by the browser and not an `::after` pseudo element on the `c-form-select` wrapper.

The problems we were seeing were on smaller screens generally on mobile devices. IE9 users would typically be within the desktop breakpoint.

Any suggestions from anyone else on this one would be welcome.

**Comment by joebell93** [comment]
@skitson perhaps we just hide the pseudo on ie9 using the conditional class?

**Comment by skitson** [comment]
@joebell93 I think that's the best, quickest, and easiest thing to do.

**Comment by joebell93** [comment]
@skitson made a few changes, what do you think?

Will post up a PR for `toolkit-core` on ie9 too

**Comment by skitson** [comment]
Yes that seems cleaner - cheers @joebell93. :shipit:

**Pull request merged**
