### PR TITLE
Changed tile default behaviour on mobile with square mod, added colla…

### PR DESCRIPTION
**Pull request by MrDinsdale**
…usable mod.

- Set default to show media and keep square ratio below medium.
- Added `.c-tile--collapsable` class which will hide media and collapse tile as before

### CODE REVIEW

**Comment by joebell93** [comment]
I think this a much more sensible approach to collapsing tiles, awesome.

:shipit:

**Comment by aaronthomas** [comment]
I think we need to find a way to deprecate this nicely, as it's very much a breaking change...

**Comment by joebell93** [comment]
Why don't we make use of sass-deprecate here?

**Comment by aaronthomas** [comment]
I'm not sure you can use sass-deprecate, given that it's not a clean deprecation of one selector in favour of another. Worth exploring though.

**Comment by MrDinsdale** [comment]
Will look in to it further, I did look at sass-deprecate however I struggled to find a solution to this.

**Comment by joebell93** [comment]
I don't think there's any safe way to deprecate this gracefully. We need to get this in but make users aware (perhaps using deprecate) that they'll need to use collapsible to hide images.

**Comment by joebell93** [comment]
:shipit:

**Pull request closed without merging**
