### PR TITLE
[Tabs] Fix scrolling navbar issue

### PR DESCRIPTION
**Pull request by JamesPeiris**
## Description
Navbar should now scroll in all view modes

## Related Issue
Closes sky-uk/toolkit#220

## How Has This Been Tested?
Tested on relevant browsers (see below)

## Types of Changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Browser Support
- [x] Chrome
- [x] Edge
- [x] Firefox
- [ ] IE9
- [x] IE10
- [x] IE11
- [x] Opera
- [x] Safari
- [x] Mobile Devices
- [x] Screen-readers (e.g. JAWS, Apple VoiceOver)

## Checklist
- [x] All code includes full inline documentation (as per the [template](https://github.com/sky-uk/toolkit-core/blob/master/_template.scss)).
- [x] All code conforms to the Toolkit [coding style](https://github.com/sky-uk/toolkit/wiki/Coding-Style).
- [x] All code conforms to [WCAG 2.0 level AA Accessibility Guidelines](https://www.w3.org/TR/WCAG20/).
- [x] New functions and mixins have appropriate tests.
- [x] All new and existing tests passed.
- [x] I have added instructions on how to test my changes.
- [x] Package version updated.
- [x] CHANGELOG.md updated.

### CODE REVIEW

**Comment by joebell93** [comment]
As stated in the issue, doesn't this make all tabs stretch to 100% width? Is that something we want?

**Comment by JamesPeiris** [comment]
We only want the tabs to be full width when specified, or when there are enough tabs that the nav bar width exceeds the container width. Met with Joe today and have a solution

**Comment by joebell93** [comment]
but in this state, surely it means the menu items will grow continuously in horizontal space?

We lose the container of our header

**Comment by joebell93** [comment]
Closing due to the [Monorepo](https://github.com/sky-uk/toolkit) move

**Pull request closed without merging**
