### PR TITLE
Fix for select button rendering issue in Safari

### PR DESCRIPTION
**Pull request by steveduffin**
If you have multiple select buttons, at certain browser widths the right hand side of a select button can be obscured (see screen shots below).

This fix moves the border style from the button to the containing label

screen shot 2016-08-12 at 14 25 05
screen shot 2016-08-12 at 14 16 48

### CODE REVIEW

**Comment by MrDinsdale** [comment]
Worth giving it a once over on other browsers but looks good to me. :shipit:

**Comment by aaronthomas** [comment]
:shipit: Thanks for this one, was causing issues for me too!

**Comment by joebell93** [comment]
@steveduffin if it's good in IE9+ I'm happy to merge!

**Comment by steveduffin** [comment]
Yep, cross browser tested on all the usual and also a Windows Lumia for a laugh

**Comment by steveduffin** [comment]
Can we get this badger merged?

**Comment by joebell93** [comment]
Smashin' stuff :shipit:

**Pull request closed without merging**
