### PR TITLE
Fix for c-bezel overflowing parent in IE

### PR DESCRIPTION
**Pull request by MrDinsdale**
## Description
`c-bezel` components will fit the content and not the parent in IE (all versions). This causes images with `c-bezel` wrappers to break layout.

screen shot 2016-09-05 at 11 28 42

## Related Issue

#130 

## How Has This Been Tested?

Browser tested in:
- IE9
- IE10
- IE11
- Edge
- Chrome (mac)
- Safari (mac)
- Firefox (mac)

These were tested on local VMs

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] New functions and mixins have appropriate tests.
- [x] All new and existing tests passed.
- [x] Changes have been browser tested (including IE).
- [x] I have added instructions on how to test my changes.
- [x] Package version updated.
- [x] CHANGELOG.md updated.

### CODE REVIEW

**Comment by joebell93** [comment]
s

**Comment by aaronthomas** [comment]
:shipit:

**Comment by joebell93** [comment]
@MrDinsdale could we add `pointer-events: none;` to the bezel too to prevent blocking of interaction on videos?

**Comment by MrDinsdale** [comment]
@joebell93 Sure, will add it in now.

**Comment by MrDinsdale** [comment]
@joebell93 ^

**Comment by joebell93** [comment]
:shipit:

**Pull request merged**
