### PR TITLE
Added fix for accordion icon alignment in IE9

### PR DESCRIPTION
**Pull request by MrDinsdale**
## Description
Added fix for icon vertical alignment

## Related Issue
#148

## Motivation and Context
Display issue on IE9

## How Has This Been Tested?
Browser tested on IE9, Chrome and Safari etc via `blackjack-accordion`

## Screenshots (if appropriate):

Before:
screen shot 2016-09-16 at 14 26 08

After:
screen shot 2016-09-16 at 14 16 41

## Types of changes
What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] New functions and mixins have appropriate tests.
- [x] All new and existing tests passed.
- [x] Changes have been browser tested (including IE).
- [x] I have added instructions on how to test my changes.
- [ ] Package version updated.
- [ ] CHANGELOG.md updated.

### CODE REVIEW

**Comment by MrDinsdale** [comment]
Not updated package no etc, will go into V1

**Comment by MrDinsdale** [comment]
Refactored to reduce amount of changes. Removal of `translateZ(0)` plus `-ms-` prefixed fixes the issue on ie9.

screen shot 2016-09-19 at 11 24 25

**Comment by joebell93** [comment]
:shipit:

**Comment by welikeideas** [comment]
Code looks good to me :shipit:

**Pull request merged**
