### PR TITLE
Adjusted select buttons to use new reduced padding

### PR DESCRIPTION
**Pull request by steveduffin**
Malin (with Dan B's blessing) has asked for all select styled buttons to be reduced from 60px left and right padding to move down to 40px

### CODE REVIEW

**Comment by MrDinsdale** [comment]
I would personally set the size explicitly here so instead of:
```$global-spacing-unit + 10px;```

I'd just use `40px;` personally but not sure what other peoples thoughts are?

**Comment by aaronthomas** [comment]
Totally agree with @MrDinsdale, the values do not need to be tied to the global spacing unit.

Other than that, LGTM.

**Comment by steveduffin** [comment]
The padding on the .c-btn--select element needs to be the same as the width declared  for the icon-with as applied tp .c-select__btn::after, so this was an attempt to link them both.

But you are right, there's no real relationship with the global unit so instead I've added comments as a note to keep them constant and used the value directly for both

**Comment by steveduffin** [comment]
Are we good to get this merged in?

**Comment by joebell93** [comment]
You'll need to update your branch to master, but looks good :shipit:

**Pull request merged**
