### PR TITLE
Table to list - responsive table component

### PR DESCRIPTION
**Pull request by skitson**
A possible solution to displaying tables with more than 2 columns as a list on small screens. Makes all table elements display block and uses pseudo CSS to give each item a heading.

Can be used on tables with or without `<thead>` section.

screen shot 2016-07-22 at 15 42 34

### CODE REVIEW

**Comment by skitson** [comment]
This component is imported anywhere at the moment...

**Comment by joebell93** [comment]
@skitson for now can I suggest putting this into your own stylesheet?

I think this will need some more investigation from the Design team before going into the Toolkit.

CC @danieljbryson

**Comment by skitson** [comment]
I've re-titled this as a table to list solution - the 'Responsive Table' title made it sound like the only solution but there are other ways to implement tables on small screens. This is just one way of doing it.

**Comment by skitson** [comment]
I now have a use case for this - I'll be implementing a version in Sky Pages Mobile Service. Specifically the for data usage statement.

**Comment by joebell93** [comment]
Awesome @skitson, probably worth bringing in @apabbott into this

**Comment by coderas** [comment]
Is anything happening with this ?

**Comment by joebell93** [comment]
We are still awaiting design.

**Comment by skitson** [comment]
I've actually implemented this in Mobile Service in a reuseable component for a statement table. Might need to have a tidy of this work but as Joe says - still waiting for design.

**Comment by joebell93** [comment]
Closing due to the [Monorepo](https://github.com/sky-uk/toolkit) move

**Comment by skitson** [comment]
😢

**Comment by joebell93** [comment]
Bring over to Toolkit! @skitson 🎈

**Pull request closed without merging**
